["a Kobold","a Beholder","a Small Cat","an Owlbear","a Displacer Beast","a Rust Monster","a Gelatinous Cube", "a Lich", "a Werebat", "a Roving Mauler", "a Knell Beetle", "a Beautiful Senmurv", "a group of Moon Rats", "a Grue", "a Gas Spore", "a Giant Space Hamster", "a Stench Kow", "a Biclops", "a Topiary Guardian", "Lolth, Demon Queen of Spiders", "an Autognome", "a Giant Vampire Frog", "an Umber Hulk", "a Wraith", "a Moth Swarm", "a Xorn", "a Lone Rot Grub", "a Chromatic Dwarf", "a Fiendish Octopus", "a Dweomerling",  "a Luminous Shark", "a Fiendish Dire Rat", "a Dizzywing Homunculus", "a Fyrthig", "a Grabby Homunculus", "a Mogwai", "a Salamander Warrior",  "a Sulking Flayer","an Aboleth Slime Mage", "an Abyssal Ant Swarm", 
"a Small Ice Elemental",
"a Medium Ice Elemental",
"a Giant Ice Elemental",
"a Collossal Ice Elemental",
"a Small Fire Elemental",
"a Medium Fire Elemental",
"a Giant Fire Elemental",
"a Collossal Fire Elemental",
"a Small Earth Elemental",
"a Medium Earth Elemental",
"a Giant Earth Elemental",
"a Collossal Earth Elemental",
"a Small Water Elemental",
"a Medium Water Elemental",
"a Giant Water Elemental",
"a Collossal Water Elemental",
"a Metal Elemental",
"an Adult White Dragon",
"an Adult Black Dragon",
"an Adult Blue Dragon",
"an Adult Red Dragon",
"an Adult Green Dragon",
"an Adult Gold Dragon",
"an Adult Silver Dragon",
"an Adult Bronze Dragon",
"an Adult Copper Dragon",
"an Adult Prismatic Dragon",

"a Juvenile White Dragon",
"a Juvenile Black Dragon",
"a Juvenile Blue Dragon",
"a Juvenile Red Dragon",
"a Juvenile Green Dragon",
"a Juvenile Gold Dragon",
"a Juvenile Silver Dragon",
"a Juvenile Bronze Dragon",
"a Juvenile Copper Dragon",
"a Juvenile Prismatic Dragon",

"an Ancient White Dragon",
"an Ancient Black Dragon",
"an Ancient Blue Dragon",
"an Ancient Red Dragon",
"an Ancient Green Dragon",
"an Ancient Gold Dragon",
"an Ancient Silver Dragon",
"an Ancient Bronze Dragon",
"an Ancient Copper Dragon",
"an Ancient Prismatic Dragon",
"a Mature White Dragon",
"a Mature Black Dragon",
"a Mature Blue Dragon",
"a Mature Red Dragon",
"a Mature Green Dragon",
"a Mature Gold Dragon",
"a Mature Silver Dragon",
"a Mature Bronze Dragon",
"a Mature Copper Dragon",
"a Mature Prismatic Dragon",
"an Accursed Rug",
"a Hobgoblin",
"an Adventuring Wizard",
"an Amoebic Crawler",
"an Amphibious Aboleth",
"an Anarchic Satyr",
"an Animated Statue",
"an Arachnoid Creature",
"an Arcane Ooze",
"an Arctic Half-Orc",
"an Astral Whale",
"an Astral Wolf",
"an Atrophied Basilisk",
"an Average Xorn",
"a Berserk Flesh Golem",
"a Black Ice Golem",
"a Blood Ghoul",
"a Blue Wyrmling",
"a Bugbear Mage",
"a Bugbear Warrior",
"a Brass Minotaur",
"a Mistling Dryad",
"a Skeletal Worg",
"a Crystalline Troll",
"a Forest Landwyrm",
"an Earthen Wyvern",
"a Caustic Creeper",
"a Cat Lord",
"a Celestial Dire Wolf",
"a Chaos Dragon",
"a Chaos Gnome",
"a Cloaked Ape",
"a Cloud Giant",
"a Colossal Skeleton",
"a Common Bat",
"a Common Orc",
"a Swamp Giant Shaman",
"a Desert Dwarf",
"a Desert Elf",
"a Desert Kobold",
"a Jungle Dwarf",
"a Jungle Halfling",
"a Kobold Miner",
"a Kobold Rat Master",
"a Kobold Skirmisher",
"a Kobold Trapmaker",
"a Dark Lord",
"a Deathglow Moth",
"a Monstrous Centipede",
"a Monstrous Scorpion",
"a Spectral Lurker",
"a Snow-Troll",
"a Slayer of Domiel",
"a Silver Sorcerer",
"a Shambling Mound",
"a Shadow Fiend",
"a Shadow Flayer",
"a Scurvy Sea Dog",
"a Salt Basilisk",
"a Runic Guardian",
"a Rope Golem",
"a Rat Burglar",
"a Questing Beast",
"a Prismatic Vortex",
"a Phrenic Manticore",
"an Orc Champion",
"an Ogre Penitent",
"a Mountain Creature",
"a Moon Elf",
"an Ogre Chieftan",
"an Ogre Petitioner",
"a Primordial Hydra",
"a Storm Giant",
"a Star Elf",
"a Star Leviathan",
"a Stalwart Paladin",
"a Troglodyte Impaler"]